web: python manage.py collectstatic --noinput && python manage.py migrate && python manage.py generate_photo_descriptions && python manage.py generate_photo_embeddings && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
worker: celery -A config worker -l info --concurrency=2
