# Generated by Django 6.0 on 2026-01-04 19:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(editable=False, max_length=16, unique=True)),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('purchaser_email', models.EmailField(max_length=254)),
                ('purchaser_name', models.CharField(blank=True, max_length=200)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True, help_text='Personal message to recipient')),
                ('is_active', models.BooleanField(default=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(choices=[('footer', 'Footer'), ('popup', 'Popup'), ('checkout', 'Checkout'), ('homepage', 'Homepage')], default='footer', max_length=20)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('mailerlite_id', models.CharField(blank=True, max_length=100)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='GiftCardRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('gift_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='core.giftcard')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gift_card_redemptions', to='orders.order')),
            ],
        ),
    ]
