# Generated by Django 6.0.1 on 2026-01-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_unique_giftcard_stripe_payment_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='source',
            field=models.CharField(choices=[('footer', 'Footer'), ('popup', 'Popup'), ('checkout', 'Checkout'), ('homepage', 'Homepage'), ('purchase', 'Purchase'), ('gift_card_purchase', 'Gift Card Purchase')], default='footer', max_length=20),
        ),
    ]
