# Generated by Django 6.0 on 2026-01-04 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='photo_title',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='variant_description',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.productvariant'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.productvariant'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', True), ('variant__isnull', False)), models.Q(('product__isnull', False), ('variant__isnull', True)), _connector='OR'), name='cart_item_has_variant_or_product'),
        ),
    ]
