# Generated by Django 6.0 on 2026-01-04 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, upload_to='collections/')),
                ('is_limited_edition', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.ImageField(upload_to='photos/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='photos/thumbnails/')),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('location_tag', models.CharField(blank=True, help_text='Lowercase tag for filtering (e.g., montauk, east-hampton)', max_length=100)),
                ('orientation', models.CharField(choices=[('H', 'Horizontal'), ('V', 'Vertical'), ('S', 'Square')], default='H', max_length=1)),
                ('date_taken', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalog.collection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(help_text='e.g., 16x24, 20x30', max_length=20)),
                ('material', models.CharField(choices=[('paper', 'Paper Print'), ('aluminum', 'Aluminum Print')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('width_inches', models.PositiveIntegerField()),
                ('height_inches', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('aluminyze_sku', models.CharField(blank=True, help_text='SKU for Aluminyze fulfillment (aluminum prints only)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.photo')),
            ],
            options={
                'ordering': ['material', 'price'],
                'unique_together': {('photo', 'size', 'material')},
            },
        ),
    ]
