# Generated by Django 6.0.1 on 2026-01-23 00:18

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_photo_image_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='ai_colors',
            field=models.JSONField(blank=True, default=list, help_text='AI-detected dominant colors (e.g., ["blue", "gold", "white"])'),
        ),
        migrations.AddField(
            model_name='photo',
            name='ai_description',
            field=models.TextField(blank=True, help_text='AI-generated rich description of the photograph'),
        ),
        migrations.AddField(
            model_name='photo',
            name='ai_mood',
            field=models.JSONField(blank=True, default=list, help_text='AI-detected mood/feeling keywords (e.g., ["calm", "dramatic"])'),
        ),
        migrations.AddField(
            model_name='photo',
            name='ai_room_suggestions',
            field=models.JSONField(blank=True, default=list, help_text='AI-suggested room types (e.g., ["bedroom", "office", "living room"])'),
        ),
        migrations.AddField(
            model_name='photo',
            name='ai_subjects',
            field=models.JSONField(blank=True, default=list, help_text='AI-detected subjects (e.g., ["lighthouse", "ocean", "sunset"])'),
        ),
        migrations.AddField(
            model_name='photo',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, help_text='Vector embedding for semantic similarity search', null=True),
        ),
    ]
