# Generated by Django 6.0.1 on 2026-01-23 00:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_alter_cartitem_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wall_analysis_id', models.CharField(blank=True, help_text='ID of wall analysis if room photo was uploaded', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(blank=True, help_text='Associated shopping cart for this conversation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='orders.cart')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool Result')], max_length=20)),
                ('content', models.TextField()),
                ('image_url', models.URLField(blank=True, help_text='URL of attached image')),
                ('tool_calls', models.JSONField(blank=True, help_text='Tool calls made by the assistant', null=True)),
                ('tool_call_id', models.CharField(blank=True, help_text='ID of the tool call this message responds to', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
