# Generated by Django 6.0.1 on 2026-01-17 23:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WallAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_image', models.ImageField(upload_to='mockups/walls/')),
                ('original_width', models.PositiveIntegerField(blank=True, null=True)),
                ('original_height', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('manual', 'Manual Selection')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('depth_map', models.ImageField(blank=True, null=True, upload_to='mockups/depth/')),
                ('wall_mask', models.ImageField(blank=True, null=True, upload_to='mockups/masks/')),
                ('wall_bounds', models.JSONField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('pixels_per_inch', models.FloatField(blank=True, null=True)),
                ('wall_height_feet', models.FloatField(default=8.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
            ],
            options={
                'verbose_name': 'Wall Analysis',
                'verbose_name_plural': 'Wall Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedMockup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mockup_image', models.ImageField(upload_to='mockups/saved/')),
                ('config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wall_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_mockups', to='mockup.wallanalysis')),
            ],
            options={
                'verbose_name': 'Saved Mockup',
                'verbose_name_plural': 'Saved Mockups',
                'ordering': ['-created_at'],
            },
        ),
    ]
