# Generated by Django 6.0.1 on 2026-01-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallanalysis',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('manual', 'Manual Selection')], db_index=True, default='pending', max_length=20),
        ),
    ]
